### ISSUE TITLE
feature/filter: Add filter tour (Search)

### ISSUE THREAD

**Issue by pum-khoa** [Triply-Organization/frontend#13]
### Requirements

Filter tours by filter including:

- Destinations
- Activity
- When
- Guests

### Tasks

- [ ] Design the interface to display the tour list after filtering
![image](https://user-images.githubusercontent.com/104960618/176158598-f2ed060a-ae7f-4402-bf66-41245f23c580.png)

- [ ] Creating Slices (Redux-toolkit)
- [ ] API Design and Call
- [ ] Get the returned data and display it on the web page
- [ ] Sort by Price
- [ ] Sort by Rating
